name: Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check format
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: "npm format:check"
